version: '3'
    
services:  
  front:
    build: ./frontend/
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/letsencrypt/:/etc/letsencrypt/
      
    
  back:
    build: ./backend/
    volumes: 
      - ../env_params/:/env_params/
      - /home/ubuntu/nltk_data/:/root/nltk_data/
    expose:
      - "8000"
    environment: 
      - GOOGLE_APPLICATION_CREDENTIALS=/env_params/private_key.json
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn interview.wsgi:application --bind 0.0.0.0:8000"
