version: "3" 
services: 
  frontend: 
    container_name: front 
    build: 
      context: frontend 
      dockerfile: front.dev.Dockerfile 
    expose: 
      - 8000 
    ports: 
      - 8000:8000
    volumes: 
      - ./frontend:/app 
      
  backend: 
    container_name: back 
    build: 
      context: backend 
      dockerfile: back.dev.Dockerfile 
    expose: 
      - 3000
    ports: 
      - 3000:3000 
    volumes: 
      - ./backend:/code
