version: '3'
    
services:  
  front:
    build: ./frontend/
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/letsencrypt/:/etc/letsencrypt/
    
  back:
    build: ./backend/
    # ports:
    #   - "8080:8080"
    expose:
      - "8080"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn interview.wsgi:application --bind 0.0.0.0:8080"
      